name: Node CI Workflow

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
  workflow_dispatch:
    inputs:
      workflowBranch:
        description: 'Select the branch to run the workflow on'
        required: true
        default: 'main'
        type: choice
        options:
          - dev
          - main
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Run CI for dev
      if: ${{ github.event.inputs.workflowBranch == 'dev' }}
      uses: shardeum/github-automation/.github/workflows/node-ci-shared.yml@dev

    - name: Run CI for main
      if: ${{ github.event.inputs.workflowBranch == 'main' || !github.event.inputs.workflowBranch }}
      uses: shardeum/github-automation/.github/workflows/node-ci-shared.yml@main